packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

allowBuilds:
  "@swc/core": true
  esbuild: true
  msgpackr-extract: true
  nx: true
  sharp: true
  unrs-resolver: true
  workerd: true

catalog:
  convex: ^1.31.7
  dotenv: ^17.4.2
  typescript: ^5
  zod: ^4.1.13

minimumReleaseAgeExclude:
  - "@cloudflare/vite-plugin@1.39.2"
  - "@storybook/addon-vitest@10.4.2"
  - "@storybook/builder-vite@10.4.2"
  - "@storybook/csf-plugin@10.4.2"
  - "@storybook/react-dom-shim@10.4.2"
  - "@storybook/react-vite@10.4.2"
  - "@storybook/react@10.4.2"
  - "@tanstack/react-router@1.170.11"
  - "@tanstack/react-start-client@1.168.8"
  - "@tanstack/react-start-rsc@0.1.18"
  - "@tanstack/react-start-server@1.167.14"
  - "@tanstack/react-start@1.168.19"
  - "@tanstack/router-core@1.171.9"
  - "@tanstack/router-generator@1.167.13"
  - "@tanstack/router-plugin@1.168.14"
  - "@tanstack/start-client-core@1.170.7"
  - "@tanstack/start-plugin-core@1.171.11"
  - "@tanstack/start-server-core@1.169.9"
  - "@tanstack/start-storage-context@1.167.11"
  - miniflare@4.20260601.0
  - storybook@10.4.2
  - wrangler@4.97.0
  - "@rspack/binding-darwin-arm64@2.0.6"
  - "@rspack/binding-darwin-x64@2.0.6"
  - "@rspack/binding-linux-arm64-gnu@2.0.6"
  - "@rspack/binding-linux-arm64-musl@2.0.6"
  - "@rspack/binding-linux-x64-gnu@2.0.6"
  - "@rspack/binding-linux-x64-musl@2.0.6"
  - "@rspack/binding-wasm32-wasi@2.0.6"
  - "@rspack/binding-win32-arm64-msvc@2.0.6"
  - "@rspack/binding-win32-ia32-msvc@2.0.6"
  - "@rspack/binding-win32-x64-msvc@2.0.6"
  - "@rspack/binding@2.0.6"
  - "@rspack/core@2.0.6"
  - "@typescript/native-preview-darwin-arm64@7.0.0-dev.20260602.1"
  - "@typescript/native-preview-darwin-x64@7.0.0-dev.20260602.1"
  - "@typescript/native-preview-linux-arm64@7.0.0-dev.20260602.1"
  - "@typescript/native-preview-linux-arm@7.0.0-dev.20260602.1"
  - "@typescript/native-preview-linux-x64@7.0.0-dev.20260602.1"
  - "@typescript/native-preview-win32-arm64@7.0.0-dev.20260602.1"
  - "@typescript/native-preview-win32-x64@7.0.0-dev.20260602.1"
  - "@typescript/native-preview@7.0.0-dev.20260602.1"
  - '@tanstack/query-core@5.101.0'
  - '@tanstack/react-query@5.101.0'
