import { createReadStream, existsSync, readdirSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

/**
 * Excalidraw resolves every font face against `window.EXCALIDRAW_ASSET_PATH`
 * (set to "/" by `loadExcalidraw` in diagram-ui) and falls back to esm.sh only
 * when that URL fails. This plugin makes "/fonts/<Family>/<file>" resolve on
 * every surface that renders Excalidraw: it serves the installed package's
 * font files in dev and emits them into the client build, so the CDN fallback
 * is never used.
 *
 * Files a surface already ships in its public directory (the vendored
 * Excalifont subsets, byte-identical to the package's) are left to that copy.
 */
const FONT_URL_PREFIX = "/fonts/";

/** Deterministic code-unit order, independent of the runtime locale. */
function byCodeUnit(left, right) {
	return left < right ? -1 : left > right ? 1 : 0;
}

const diagramUi = createRequire(new URL("../../packages/diagram/ui/package.json", import.meta.url));

export function excalidrawFontsDirectory() {
	// Resolve through diagram-ui, which owns the Excalidraw dependency.
	return join(dirname(diagramUi.resolve("@excalidraw/excalidraw")), "fonts");
}

/** Font files relative to the fonts directory, e.g. "Xiaolai/Xiaolai-Regular-<hash>.woff2". */
export function excalidrawFontFiles(directory = excalidrawFontsDirectory()) {
	return readdirSync(directory, { recursive: true, withFileTypes: true })
		.filter((entry) => entry.isFile() && entry.name.endsWith(".woff2"))
		.map((entry) =>
			join(entry.parentPath, entry.name)
				.slice(directory.length + 1)
				.replaceAll("\\", "/"),
		)
		.sort(byCodeUnit);
}

const CONTENT_HASHED = /-[0-9a-f]{32}\.woff2$/;
const IMMUTABLE = "public, max-age=31536000, immutable";
const REVALIDATED = "public, max-age=86400";

/**
 * Workers static-assets `_headers` rules for the served fonts. Families whose
 * every file name carries a content hash are cached immutably; families with
 * stable names (Cascadia, Virgil, Assistant, ...) can change in place on an
 * Excalidraw upgrade, so they are cached for a day. Each surface that serves
 * the fonts ships this block verbatim in `public/_headers`; a test keeps them
 * in sync with the installed package.
 */
export function excalidrawFontHeaders(files = excalidrawFontFiles()) {
	const families = new Map();
	for (const file of files) {
		const [family] = file.split("/");
		families.set(family, (families.get(family) ?? true) && CONTENT_HASHED.test(file));
	}
	return [
		"# Excalidraw fonts, generated by excalidrawFontHeaders() in",
		"# scripts/lib/excalidraw-fonts.mjs. Keep this block in sync.",
		...[...families.keys()]
			.sort(byCodeUnit)
			.flatMap((family) => [
				`${FONT_URL_PREFIX}${family}/*`,
				`  Cache-Control: ${families.get(family) ? IMMUTABLE : REVALIDATED}`,
			]),
		"",
	].join("\n");
}

/** @returns {import("vite").Plugin} */
export function excalidrawFonts() {
	const directory = excalidrawFontsDirectory();
	const files = new Set(excalidrawFontFiles(directory));
	let publicDirectory = "";

	return {
		name: "sketchi:excalidraw-fonts",
		configResolved(config) {
			publicDirectory = config.publicDir;
		},
		configureServer(server) {
			server.middlewares.use(FONT_URL_PREFIX, (request, response, next) => {
				const file = decodeURIComponent((request.url ?? "").split("?")[0] ?? "").replace(
					/^\/+/,
					"",
				);
				if (!files.has(file)) {
					next();
					return;
				}
				response.setHeader("content-type", "font/woff2");
				createReadStream(join(directory, file)).pipe(response);
			});
		},
		applyToEnvironment(environment) {
			return environment.name === "client";
		},
		generateBundle() {
			for (const file of files) {
				const fileName = `fonts/${file}`;
				if (publicDirectory && existsSync(join(publicDirectory, fileName))) {
					continue;
				}
				this.emitFile({
					type: "asset",
					fileName,
					source: readFileSync(join(directory, file)),
				});
			}
		},
	};
}
