/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as McpRouteImport } from "./routes/mcp";
import { Route as CodemodeExportHarnessRouteImport } from "./routes/codemode-export-harness";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ArtifactsArtifactIdRouteImport } from "./routes/artifacts/$artifactId";
import { Route as ApiChatRouteImport } from "./routes/api/chat";
import { Route as ApiPlaygroundArtifactsRouteImport } from "./routes/api/playground/artifacts";
import { Route as ApiV1FlowchartsBuildRouteImport } from "./routes/api/v1/flowcharts/build";
import { Route as ApiV1ArtifactsArtifactIdRouteImport } from "./routes/api/v1/artifacts/$artifactId";
import { Route as ApiV1ArtifactsArtifactIdPatchRouteImport } from "./routes/api/v1/artifacts/$artifactId/patch";

const McpRoute = McpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => rootRouteImport,
} as any);
const CodemodeExportHarnessRoute = CodemodeExportHarnessRouteImport.update({
  id: "/codemode-export-harness",
  path: "/codemode-export-harness",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: "/artifacts/$artifactId",
  path: "/artifacts/$artifactId",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiChatRoute = ApiChatRouteImport.update({
  id: "/api/chat",
  path: "/api/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiPlaygroundArtifactsRoute = ApiPlaygroundArtifactsRouteImport.update({
  id: "/api/playground/artifacts",
  path: "/api/playground/artifacts",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1FlowchartsBuildRoute = ApiV1FlowchartsBuildRouteImport.update({
  id: "/api/v1/flowcharts/build",
  path: "/api/v1/flowcharts/build",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1ArtifactsArtifactIdRoute =
  ApiV1ArtifactsArtifactIdRouteImport.update({
    id: "/api/v1/artifacts/$artifactId",
    path: "/api/v1/artifacts/$artifactId",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiV1ArtifactsArtifactIdPatchRoute =
  ApiV1ArtifactsArtifactIdPatchRouteImport.update({
    id: "/patch",
    path: "/patch",
    getParentRoute: () => ApiV1ArtifactsArtifactIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/codemode-export-harness": typeof CodemodeExportHarnessRoute;
  "/mcp": typeof McpRoute;
  "/api/chat": typeof ApiChatRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/api/playground/artifacts": typeof ApiPlaygroundArtifactsRoute;
  "/api/v1/artifacts/$artifactId": typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  "/api/v1/flowcharts/build": typeof ApiV1FlowchartsBuildRoute;
  "/api/v1/artifacts/$artifactId/patch": typeof ApiV1ArtifactsArtifactIdPatchRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/codemode-export-harness": typeof CodemodeExportHarnessRoute;
  "/mcp": typeof McpRoute;
  "/api/chat": typeof ApiChatRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/api/playground/artifacts": typeof ApiPlaygroundArtifactsRoute;
  "/api/v1/artifacts/$artifactId": typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  "/api/v1/flowcharts/build": typeof ApiV1FlowchartsBuildRoute;
  "/api/v1/artifacts/$artifactId/patch": typeof ApiV1ArtifactsArtifactIdPatchRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/codemode-export-harness": typeof CodemodeExportHarnessRoute;
  "/mcp": typeof McpRoute;
  "/api/chat": typeof ApiChatRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/api/playground/artifacts": typeof ApiPlaygroundArtifactsRoute;
  "/api/v1/artifacts/$artifactId": typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  "/api/v1/flowcharts/build": typeof ApiV1FlowchartsBuildRoute;
  "/api/v1/artifacts/$artifactId/patch": typeof ApiV1ArtifactsArtifactIdPatchRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/codemode-export-harness"
    | "/mcp"
    | "/api/chat"
    | "/artifacts/$artifactId"
    | "/api/playground/artifacts"
    | "/api/v1/artifacts/$artifactId"
    | "/api/v1/flowcharts/build"
    | "/api/v1/artifacts/$artifactId/patch";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/codemode-export-harness"
    | "/mcp"
    | "/api/chat"
    | "/artifacts/$artifactId"
    | "/api/playground/artifacts"
    | "/api/v1/artifacts/$artifactId"
    | "/api/v1/flowcharts/build"
    | "/api/v1/artifacts/$artifactId/patch";
  id:
    | "__root__"
    | "/"
    | "/codemode-export-harness"
    | "/mcp"
    | "/api/chat"
    | "/artifacts/$artifactId"
    | "/api/playground/artifacts"
    | "/api/v1/artifacts/$artifactId"
    | "/api/v1/flowcharts/build"
    | "/api/v1/artifacts/$artifactId/patch";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CodemodeExportHarnessRoute: typeof CodemodeExportHarnessRoute;
  McpRoute: typeof McpRoute;
  ApiChatRoute: typeof ApiChatRoute;
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRoute;
  ApiPlaygroundArtifactsRoute: typeof ApiPlaygroundArtifactsRoute;
  ApiV1ArtifactsArtifactIdRoute: typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  ApiV1FlowchartsBuildRoute: typeof ApiV1FlowchartsBuildRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/mcp": {
      id: "/mcp";
      path: "/mcp";
      fullPath: "/mcp";
      preLoaderRoute: typeof McpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/codemode-export-harness": {
      id: "/codemode-export-harness";
      path: "/codemode-export-harness";
      fullPath: "/codemode-export-harness";
      preLoaderRoute: typeof CodemodeExportHarnessRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artifacts/$artifactId": {
      id: "/artifacts/$artifactId";
      path: "/artifacts/$artifactId";
      fullPath: "/artifacts/$artifactId";
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/chat": {
      id: "/api/chat";
      path: "/api/chat";
      fullPath: "/api/chat";
      preLoaderRoute: typeof ApiChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/playground/artifacts": {
      id: "/api/playground/artifacts";
      path: "/api/playground/artifacts";
      fullPath: "/api/playground/artifacts";
      preLoaderRoute: typeof ApiPlaygroundArtifactsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/flowcharts/build": {
      id: "/api/v1/flowcharts/build";
      path: "/api/v1/flowcharts/build";
      fullPath: "/api/v1/flowcharts/build";
      preLoaderRoute: typeof ApiV1FlowchartsBuildRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/artifacts/$artifactId": {
      id: "/api/v1/artifacts/$artifactId";
      path: "/api/v1/artifacts/$artifactId";
      fullPath: "/api/v1/artifacts/$artifactId";
      preLoaderRoute: typeof ApiV1ArtifactsArtifactIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/artifacts/$artifactId/patch": {
      id: "/api/v1/artifacts/$artifactId/patch";
      path: "/patch";
      fullPath: "/api/v1/artifacts/$artifactId/patch";
      preLoaderRoute: typeof ApiV1ArtifactsArtifactIdPatchRouteImport;
      parentRoute: typeof ApiV1ArtifactsArtifactIdRoute;
    };
  }
}

interface ApiV1ArtifactsArtifactIdRouteChildren {
  ApiV1ArtifactsArtifactIdPatchRoute: typeof ApiV1ArtifactsArtifactIdPatchRoute;
}

const ApiV1ArtifactsArtifactIdRouteChildren: ApiV1ArtifactsArtifactIdRouteChildren =
  {
    ApiV1ArtifactsArtifactIdPatchRoute: ApiV1ArtifactsArtifactIdPatchRoute,
  };

const ApiV1ArtifactsArtifactIdRouteWithChildren =
  ApiV1ArtifactsArtifactIdRoute._addFileChildren(
    ApiV1ArtifactsArtifactIdRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodemodeExportHarnessRoute: CodemodeExportHarnessRoute,
  McpRoute: McpRoute,
  ApiChatRoute: ApiChatRoute,
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRoute,
  ApiPlaygroundArtifactsRoute: ApiPlaygroundArtifactsRoute,
  ApiV1ArtifactsArtifactIdRoute: ApiV1ArtifactsArtifactIdRouteWithChildren,
  ApiV1FlowchartsBuildRoute: ApiV1FlowchartsBuildRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
