import { strict as assert } from "node:assert";

import { describe, it } from "@effect/vitest";
import { Effect } from "effect";

import {
  EXCALIDRAW_BASELINE_COMMIT,
  EXCALIDRAW_STORE_BASELINE_COMMIT,
  decodeSharePayload,
  encodeSharePayload,
  formatShareLink,
  parseShareLink,
  serializeForShare,
  validateShareScene,
} from "./share-protocol.js";

const fixtureKey = "AAAAAAAAAAAAAAAAAAAAAA";
const fixtureIv = Uint8Array.from({ length: 12 }, (_, index) => index);
const fixtureJson =
  '{"type":"excalidraw","version":2,"source":"fixture","elements":[],"appState":{}}';

// Recorded with Excalidraw compressData at the pinned baseline using the
// fixed key/IV above. This is an interoperability fixture, not regenerated by
// the implementation under test.
const upstreamFixtureBase64 =
  "AAAAAQAAADt7InZlcnNpb24iOjIsImNvbXByZXNzaW9uIjoicGFrb0AxIiwiZW5jcnlwdGlvbiI6IkFFUy1HQ00ifQAAAAwAAQIDBAUGBwgJCgsAAABwS0FmJqaMrQb1t7tGQcGwgA4SZcyKsmKKKAOPGVtpp3rmpxH09x+3tCmigYL0JVNUhroYaQnEUAQO3xrbxSLUOHzf1Dqd34h2udD2ajvavYTylPF0qu/YiNffWt3Et/n0vqmnXlUaNEWJ68C2UnYinw==";

describe("Excalidraw share-link protocol", () => {
  it("pins the independently reviewed upstream revisions", () => {
    assert.equal(
      EXCALIDRAW_BASELINE_COMMIT,
      "e6ae6bf05755eb3845d9635953bd6477e948a8f6",
    );
    assert.equal(
      EXCALIDRAW_STORE_BASELINE_COMMIT,
      "76de642d0e9961f26bf6c1fe1dbe1aeaac5c5778",
    );
  });

  it.effect("decrypts the recorded upstream format-v2 fixture", () =>
    Effect.gen(function* () {
      const decoded = yield* decodeSharePayload(
        Buffer.from(upstreamFixtureBase64, "base64"),
        fixtureKey,
      );
      assert.deepEqual(decoded, JSON.parse(fixtureJson));
    }),
  );

  it.effect("encodes a format-v2 payload that round-trips", () =>
    Effect.gen(function* () {
      const encoded = yield* encodeSharePayload(
        new TextEncoder().encode(fixtureJson),
        fixtureKey,
        fixtureIv,
      );
      assert.deepEqual(
        yield* decodeSharePayload(encoded, fixtureKey),
        JSON.parse(fixtureJson),
      );
      assert.equal(
        Buffer.from(encoded).toString("base64"),
        upstreamFixtureBase64,
      );
    }),
  );

  it.effect("rejects tampering without leaking key material", () =>
    Effect.gen(function* () {
      const body = Buffer.from(upstreamFixtureBase64, "base64");
      body[body.length - 1] = (body[body.length - 1] ?? 0) ^ 1;
      const failure = yield* Effect.flip(decodeSharePayload(body, fixtureKey));
      assert.equal(failure.code, "share_crypto_failed");
      assert.equal(failure.message.includes(fixtureKey), false);
    }),
  );

  it.effect("parses only strict root Excalidraw share URLs", () =>
    Effect.gen(function* () {
      const expected = { id: "example_123", key: fixtureKey };
      assert.deepEqual(
        yield* parseShareLink(formatShareLink(expected)),
        expected,
      );
      assert.deepEqual(
        yield* parseShareLink(
          `https://www.excalidraw.com/#json=${expected.id},${expected.key}`,
        ),
        expected,
      );
      for (const invalid of [
        `http://excalidraw.com/#json=${expected.id},${expected.key}`,
        `https://evil.invalid/#json=${expected.id},${expected.key}`,
        `https://EXCALIDRAW.com/#json=${expected.id},${expected.key}`,
        `https://user@excalidraw.com/#json=${expected.id},${expected.key}`,
        `https://excalidraw.com:443/#json=${expected.id},${expected.key}`,
        `https://excalidraw.com/path#json=${expected.id},${expected.key}`,
        `https://excalidraw.com/?x=1#json=${expected.id},${expected.key}`,
      ]) {
        assert.equal(
          (yield* Effect.flip(parseShareLink(invalid))).code,
          "invalid_share_link",
        );
      }
    }),
  );

  it.effect("serializes database app state and omits files", () =>
    Effect.gen(function* () {
      const serialized = yield* serializeForShare({
        type: "excalidraw",
        version: 2,
        source: "https://sketchi.app",
        elements: [],
        appState: {
          viewBackgroundColor: "#fff",
          zoom: { value: 0.5 },
          gridModeEnabled: true,
          lockedMultiSelections: { group: true },
        },
        files: {},
      });
      assert.deepEqual(JSON.parse(new TextDecoder().decode(serialized)), {
        type: "excalidraw",
        version: 2,
        source: "https://sketchi.app",
        elements: [],
        appState: {
          gridModeEnabled: true,
          viewBackgroundColor: "#fff",
          lockedMultiSelections: { group: true },
        },
      });
    }),
  );

  it.effect("validates finite geometry, bindings, and database app state", () =>
    Effect.gen(function* () {
      const element = {
        id: "one",
        type: "rectangle",
        x: 0,
        y: 0,
        width: 10,
        height: 10,
        angle: 0,
      };
      const base = {
        type: "excalidraw",
        version: 2,
        source: "fixture",
        elements: [element],
        appState: {},
        files: {},
      };
      for (const scene of [
        { ...base, elements: [{ ...element, strokeWidth: Infinity }] },
        { ...base, elements: [{ ...element, frameId: "missing" }] },
        { ...base, elements: [{ ...element, width: 6000, height: 6000 }] },
        { ...base, appState: { gridSize: Infinity } },
        { ...base, appState: { lockedMultiSelections: { group: false } } },
      ]) {
        const failure = yield* Effect.flip(validateShareScene(scene));
        assert.equal(failure.code, "unsupported_scene");
      }

      const secretType = "attacker-secret-element";
      const failure = yield* Effect.flip(
        validateShareScene({
          ...base,
          elements: [{ ...element, type: secretType }],
        }),
      );
      assert.equal(JSON.stringify(failure).includes(secretType), false);
    }),
  );

  it.effect(
    "rejects files, images, unsupported types, and non-Excalifont text",
    () =>
      Effect.gen(function* () {
        const base = {
          type: "excalidraw",
          version: 2,
          source: "fixture",
          appState: {},
          files: {},
        };
        const element = {
          id: "one",
          type: "rectangle",
          x: 0,
          y: 0,
          width: 10,
          height: 10,
          angle: 0,
        };
        for (const scene of [
          { ...base, elements: [], files: { file: {} } },
          { ...base, elements: [{ ...element, type: "image" }] },
          { ...base, elements: [{ ...element, type: "frame" }] },
          { ...base, elements: [{ ...element, type: "text", fontFamily: 1 }] },
          { ...base, elements: [{ ...element, link: "https://example.com" }] },
        ]) {
          assert.equal(
            (yield* Effect.flip(validateShareScene(scene))).code,
            "unsupported_scene",
          );
        }
      }),
  );

  it.effect("bounds compression before encryption and final framing", () =>
    Effect.gen(function* () {
      const oversized = new Uint8Array(3 * 1024 * 1024);
      let state = 0x12345678;
      for (let index = 0; index < oversized.byteLength; index += 1) {
        state ^= state << 13;
        state ^= state >>> 17;
        state ^= state << 5;
        oversized[index] = state & 0xff;
      }
      const failure = yield* Effect.flip(
        encodeSharePayload(oversized, "invalid-key", fixtureIv),
      );
      assert.equal(failure.code, "share_payload_too_large");
    }),
  );

  it.effect("rejects zero-length and high-count chunk tables directly", () =>
    Effect.gen(function* () {
      const zeroLengthChunks = new Uint8Array(16);
      new DataView(zeroLengthChunks.buffer).setUint32(0, 1);
      const zeroFailure = yield* Effect.flip(
        decodeSharePayload(zeroLengthChunks, fixtureKey),
      );
      assert.equal(zeroFailure.code, "share_crypto_failed");

      const highCountProbe = new Uint8Array(2 * 1024 * 1024);
      new DataView(highCountProbe.buffer).setUint32(0, 1);
      const highCountFailure = yield* Effect.flip(
        decodeSharePayload(highCountProbe, fixtureKey),
      );
      assert.equal(highCountFailure.code, "share_crypto_failed");
    }),
  );
});
