/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProjectsRouteImport } from "./routes/projects";
import { Route as McpRouteImport } from "./routes/mcp";
import { Route as CodemodeExportHarnessRouteImport } from "./routes/codemode-export-harness";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects_/$projectId";
import { Route as ExamplesExampleIdRouteImport } from "./routes/examples/$exampleId";
import { Route as DiagramsDiagramIdRouteImport } from "./routes/diagrams/$diagramId";
import { Route as ArtifactsArtifactIdRouteImport } from "./routes/artifacts/$artifactId";
import { Route as ApiChatRouteImport } from "./routes/api/chat";
import { Route as DiagramsDiagramIdEditRouteImport } from "./routes/diagrams_/$diagramId/edit";
import { Route as ArtifactsArtifactIdEditRouteImport } from "./routes/artifacts_/$artifactId/edit";
import { Route as ApiV1GenerateRouteImport } from "./routes/api/v1/generate";
import { Route as ApiStudioProjectsRouteImport } from "./routes/api/studio/projects";
import { Route as ApiV1SequencesBuildRouteImport } from "./routes/api/v1/sequences/build";
import { Route as ApiV1MindmapsBuildRouteImport } from "./routes/api/v1/mindmaps/build";
import { Route as ApiV1FlowchartsBuildRouteImport } from "./routes/api/v1/flowcharts/build";
import { Route as ApiV1ArtifactsArtifactIdRouteImport } from "./routes/api/v1/artifacts/$artifactId";
import { Route as ApiStudioProjectsProjectIdRouteImport } from "./routes/api/studio/projects_/$projectId";
import { Route as ApiStudioProjectsFromArtifactRouteImport } from "./routes/api/studio/projects/from-artifact";
import { Route as ApiStudioDiagramsDiagramIdRouteImport } from "./routes/api/studio/diagrams/$diagramId";
import { Route as ApiV1ArtifactsArtifactIdPatchRouteImport } from "./routes/api/v1/artifacts/$artifactId/patch";

const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const McpRoute = McpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => rootRouteImport,
} as any);
const CodemodeExportHarnessRoute = CodemodeExportHarnessRouteImport.update({
  id: "/codemode-export-harness",
  path: "/codemode-export-harness",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/projects_/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const ExamplesExampleIdRoute = ExamplesExampleIdRouteImport.update({
  id: "/examples/$exampleId",
  path: "/examples/$exampleId",
  getParentRoute: () => rootRouteImport,
} as any);
const DiagramsDiagramIdRoute = DiagramsDiagramIdRouteImport.update({
  id: "/diagrams/$diagramId",
  path: "/diagrams/$diagramId",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: "/artifacts/$artifactId",
  path: "/artifacts/$artifactId",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiChatRoute = ApiChatRouteImport.update({
  id: "/api/chat",
  path: "/api/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const DiagramsDiagramIdEditRoute = DiagramsDiagramIdEditRouteImport.update({
  id: "/diagrams_/$diagramId/edit",
  path: "/diagrams/$diagramId/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtifactsArtifactIdEditRoute = ArtifactsArtifactIdEditRouteImport.update({
  id: "/artifacts_/$artifactId/edit",
  path: "/artifacts/$artifactId/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1GenerateRoute = ApiV1GenerateRouteImport.update({
  id: "/api/v1/generate",
  path: "/api/v1/generate",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiStudioProjectsRoute = ApiStudioProjectsRouteImport.update({
  id: "/api/studio/projects",
  path: "/api/studio/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1SequencesBuildRoute = ApiV1SequencesBuildRouteImport.update({
  id: "/api/v1/sequences/build",
  path: "/api/v1/sequences/build",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1MindmapsBuildRoute = ApiV1MindmapsBuildRouteImport.update({
  id: "/api/v1/mindmaps/build",
  path: "/api/v1/mindmaps/build",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1FlowchartsBuildRoute = ApiV1FlowchartsBuildRouteImport.update({
  id: "/api/v1/flowcharts/build",
  path: "/api/v1/flowcharts/build",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1ArtifactsArtifactIdRoute =
  ApiV1ArtifactsArtifactIdRouteImport.update({
    id: "/api/v1/artifacts/$artifactId",
    path: "/api/v1/artifacts/$artifactId",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiStudioProjectsProjectIdRoute =
  ApiStudioProjectsProjectIdRouteImport.update({
    id: "/api/studio/projects_/$projectId",
    path: "/api/studio/projects/$projectId",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiStudioProjectsFromArtifactRoute =
  ApiStudioProjectsFromArtifactRouteImport.update({
    id: "/from-artifact",
    path: "/from-artifact",
    getParentRoute: () => ApiStudioProjectsRoute,
  } as any);
const ApiStudioDiagramsDiagramIdRoute =
  ApiStudioDiagramsDiagramIdRouteImport.update({
    id: "/api/studio/diagrams/$diagramId",
    path: "/api/studio/diagrams/$diagramId",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiV1ArtifactsArtifactIdPatchRoute =
  ApiV1ArtifactsArtifactIdPatchRouteImport.update({
    id: "/patch",
    path: "/patch",
    getParentRoute: () => ApiV1ArtifactsArtifactIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/codemode-export-harness": typeof CodemodeExportHarnessRoute;
  "/mcp": typeof McpRoute;
  "/projects": typeof ProjectsRoute;
  "/api/chat": typeof ApiChatRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/diagrams/$diagramId": typeof DiagramsDiagramIdRoute;
  "/examples/$exampleId": typeof ExamplesExampleIdRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/api/studio/projects": typeof ApiStudioProjectsRouteWithChildren;
  "/api/v1/generate": typeof ApiV1GenerateRoute;
  "/artifacts/$artifactId/edit": typeof ArtifactsArtifactIdEditRoute;
  "/diagrams/$diagramId/edit": typeof DiagramsDiagramIdEditRoute;
  "/api/studio/diagrams/$diagramId": typeof ApiStudioDiagramsDiagramIdRoute;
  "/api/studio/projects/from-artifact": typeof ApiStudioProjectsFromArtifactRoute;
  "/api/studio/projects/$projectId": typeof ApiStudioProjectsProjectIdRoute;
  "/api/v1/artifacts/$artifactId": typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  "/api/v1/flowcharts/build": typeof ApiV1FlowchartsBuildRoute;
  "/api/v1/mindmaps/build": typeof ApiV1MindmapsBuildRoute;
  "/api/v1/sequences/build": typeof ApiV1SequencesBuildRoute;
  "/api/v1/artifacts/$artifactId/patch": typeof ApiV1ArtifactsArtifactIdPatchRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/codemode-export-harness": typeof CodemodeExportHarnessRoute;
  "/mcp": typeof McpRoute;
  "/projects": typeof ProjectsRoute;
  "/api/chat": typeof ApiChatRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/diagrams/$diagramId": typeof DiagramsDiagramIdRoute;
  "/examples/$exampleId": typeof ExamplesExampleIdRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/api/studio/projects": typeof ApiStudioProjectsRouteWithChildren;
  "/api/v1/generate": typeof ApiV1GenerateRoute;
  "/artifacts/$artifactId/edit": typeof ArtifactsArtifactIdEditRoute;
  "/diagrams/$diagramId/edit": typeof DiagramsDiagramIdEditRoute;
  "/api/studio/diagrams/$diagramId": typeof ApiStudioDiagramsDiagramIdRoute;
  "/api/studio/projects/from-artifact": typeof ApiStudioProjectsFromArtifactRoute;
  "/api/studio/projects/$projectId": typeof ApiStudioProjectsProjectIdRoute;
  "/api/v1/artifacts/$artifactId": typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  "/api/v1/flowcharts/build": typeof ApiV1FlowchartsBuildRoute;
  "/api/v1/mindmaps/build": typeof ApiV1MindmapsBuildRoute;
  "/api/v1/sequences/build": typeof ApiV1SequencesBuildRoute;
  "/api/v1/artifacts/$artifactId/patch": typeof ApiV1ArtifactsArtifactIdPatchRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/codemode-export-harness": typeof CodemodeExportHarnessRoute;
  "/mcp": typeof McpRoute;
  "/projects": typeof ProjectsRoute;
  "/api/chat": typeof ApiChatRoute;
  "/artifacts/$artifactId": typeof ArtifactsArtifactIdRoute;
  "/diagrams/$diagramId": typeof DiagramsDiagramIdRoute;
  "/examples/$exampleId": typeof ExamplesExampleIdRoute;
  "/projects_/$projectId": typeof ProjectsProjectIdRoute;
  "/api/studio/projects": typeof ApiStudioProjectsRouteWithChildren;
  "/api/v1/generate": typeof ApiV1GenerateRoute;
  "/artifacts_/$artifactId/edit": typeof ArtifactsArtifactIdEditRoute;
  "/diagrams_/$diagramId/edit": typeof DiagramsDiagramIdEditRoute;
  "/api/studio/diagrams/$diagramId": typeof ApiStudioDiagramsDiagramIdRoute;
  "/api/studio/projects/from-artifact": typeof ApiStudioProjectsFromArtifactRoute;
  "/api/studio/projects_/$projectId": typeof ApiStudioProjectsProjectIdRoute;
  "/api/v1/artifacts/$artifactId": typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  "/api/v1/flowcharts/build": typeof ApiV1FlowchartsBuildRoute;
  "/api/v1/mindmaps/build": typeof ApiV1MindmapsBuildRoute;
  "/api/v1/sequences/build": typeof ApiV1SequencesBuildRoute;
  "/api/v1/artifacts/$artifactId/patch": typeof ApiV1ArtifactsArtifactIdPatchRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/codemode-export-harness"
    | "/mcp"
    | "/projects"
    | "/api/chat"
    | "/artifacts/$artifactId"
    | "/diagrams/$diagramId"
    | "/examples/$exampleId"
    | "/projects/$projectId"
    | "/api/studio/projects"
    | "/api/v1/generate"
    | "/artifacts/$artifactId/edit"
    | "/diagrams/$diagramId/edit"
    | "/api/studio/diagrams/$diagramId"
    | "/api/studio/projects/from-artifact"
    | "/api/studio/projects/$projectId"
    | "/api/v1/artifacts/$artifactId"
    | "/api/v1/flowcharts/build"
    | "/api/v1/mindmaps/build"
    | "/api/v1/sequences/build"
    | "/api/v1/artifacts/$artifactId/patch";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/codemode-export-harness"
    | "/mcp"
    | "/projects"
    | "/api/chat"
    | "/artifacts/$artifactId"
    | "/diagrams/$diagramId"
    | "/examples/$exampleId"
    | "/projects/$projectId"
    | "/api/studio/projects"
    | "/api/v1/generate"
    | "/artifacts/$artifactId/edit"
    | "/diagrams/$diagramId/edit"
    | "/api/studio/diagrams/$diagramId"
    | "/api/studio/projects/from-artifact"
    | "/api/studio/projects/$projectId"
    | "/api/v1/artifacts/$artifactId"
    | "/api/v1/flowcharts/build"
    | "/api/v1/mindmaps/build"
    | "/api/v1/sequences/build"
    | "/api/v1/artifacts/$artifactId/patch";
  id:
    | "__root__"
    | "/"
    | "/codemode-export-harness"
    | "/mcp"
    | "/projects"
    | "/api/chat"
    | "/artifacts/$artifactId"
    | "/diagrams/$diagramId"
    | "/examples/$exampleId"
    | "/projects_/$projectId"
    | "/api/studio/projects"
    | "/api/v1/generate"
    | "/artifacts_/$artifactId/edit"
    | "/diagrams_/$diagramId/edit"
    | "/api/studio/diagrams/$diagramId"
    | "/api/studio/projects/from-artifact"
    | "/api/studio/projects_/$projectId"
    | "/api/v1/artifacts/$artifactId"
    | "/api/v1/flowcharts/build"
    | "/api/v1/mindmaps/build"
    | "/api/v1/sequences/build"
    | "/api/v1/artifacts/$artifactId/patch";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CodemodeExportHarnessRoute: typeof CodemodeExportHarnessRoute;
  McpRoute: typeof McpRoute;
  ProjectsRoute: typeof ProjectsRoute;
  ApiChatRoute: typeof ApiChatRoute;
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRoute;
  DiagramsDiagramIdRoute: typeof DiagramsDiagramIdRoute;
  ExamplesExampleIdRoute: typeof ExamplesExampleIdRoute;
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute;
  ApiStudioProjectsRoute: typeof ApiStudioProjectsRouteWithChildren;
  ApiV1GenerateRoute: typeof ApiV1GenerateRoute;
  ArtifactsArtifactIdEditRoute: typeof ArtifactsArtifactIdEditRoute;
  DiagramsDiagramIdEditRoute: typeof DiagramsDiagramIdEditRoute;
  ApiStudioDiagramsDiagramIdRoute: typeof ApiStudioDiagramsDiagramIdRoute;
  ApiStudioProjectsProjectIdRoute: typeof ApiStudioProjectsProjectIdRoute;
  ApiV1ArtifactsArtifactIdRoute: typeof ApiV1ArtifactsArtifactIdRouteWithChildren;
  ApiV1FlowchartsBuildRoute: typeof ApiV1FlowchartsBuildRoute;
  ApiV1MindmapsBuildRoute: typeof ApiV1MindmapsBuildRoute;
  ApiV1SequencesBuildRoute: typeof ApiV1SequencesBuildRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof ProjectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mcp": {
      id: "/mcp";
      path: "/mcp";
      fullPath: "/mcp";
      preLoaderRoute: typeof McpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/codemode-export-harness": {
      id: "/codemode-export-harness";
      path: "/codemode-export-harness";
      fullPath: "/codemode-export-harness";
      preLoaderRoute: typeof CodemodeExportHarnessRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects_/$projectId": {
      id: "/projects_/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof ProjectsProjectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/examples/$exampleId": {
      id: "/examples/$exampleId";
      path: "/examples/$exampleId";
      fullPath: "/examples/$exampleId";
      preLoaderRoute: typeof ExamplesExampleIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/diagrams/$diagramId": {
      id: "/diagrams/$diagramId";
      path: "/diagrams/$diagramId";
      fullPath: "/diagrams/$diagramId";
      preLoaderRoute: typeof DiagramsDiagramIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artifacts/$artifactId": {
      id: "/artifacts/$artifactId";
      path: "/artifacts/$artifactId";
      fullPath: "/artifacts/$artifactId";
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/chat": {
      id: "/api/chat";
      path: "/api/chat";
      fullPath: "/api/chat";
      preLoaderRoute: typeof ApiChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/diagrams_/$diagramId/edit": {
      id: "/diagrams_/$diagramId/edit";
      path: "/diagrams/$diagramId/edit";
      fullPath: "/diagrams/$diagramId/edit";
      preLoaderRoute: typeof DiagramsDiagramIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artifacts_/$artifactId/edit": {
      id: "/artifacts_/$artifactId/edit";
      path: "/artifacts/$artifactId/edit";
      fullPath: "/artifacts/$artifactId/edit";
      preLoaderRoute: typeof ArtifactsArtifactIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/generate": {
      id: "/api/v1/generate";
      path: "/api/v1/generate";
      fullPath: "/api/v1/generate";
      preLoaderRoute: typeof ApiV1GenerateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/studio/projects": {
      id: "/api/studio/projects";
      path: "/api/studio/projects";
      fullPath: "/api/studio/projects";
      preLoaderRoute: typeof ApiStudioProjectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/sequences/build": {
      id: "/api/v1/sequences/build";
      path: "/api/v1/sequences/build";
      fullPath: "/api/v1/sequences/build";
      preLoaderRoute: typeof ApiV1SequencesBuildRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/mindmaps/build": {
      id: "/api/v1/mindmaps/build";
      path: "/api/v1/mindmaps/build";
      fullPath: "/api/v1/mindmaps/build";
      preLoaderRoute: typeof ApiV1MindmapsBuildRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/flowcharts/build": {
      id: "/api/v1/flowcharts/build";
      path: "/api/v1/flowcharts/build";
      fullPath: "/api/v1/flowcharts/build";
      preLoaderRoute: typeof ApiV1FlowchartsBuildRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/artifacts/$artifactId": {
      id: "/api/v1/artifacts/$artifactId";
      path: "/api/v1/artifacts/$artifactId";
      fullPath: "/api/v1/artifacts/$artifactId";
      preLoaderRoute: typeof ApiV1ArtifactsArtifactIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/studio/projects_/$projectId": {
      id: "/api/studio/projects_/$projectId";
      path: "/api/studio/projects/$projectId";
      fullPath: "/api/studio/projects/$projectId";
      preLoaderRoute: typeof ApiStudioProjectsProjectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/studio/projects/from-artifact": {
      id: "/api/studio/projects/from-artifact";
      path: "/from-artifact";
      fullPath: "/api/studio/projects/from-artifact";
      preLoaderRoute: typeof ApiStudioProjectsFromArtifactRouteImport;
      parentRoute: typeof ApiStudioProjectsRoute;
    };
    "/api/studio/diagrams/$diagramId": {
      id: "/api/studio/diagrams/$diagramId";
      path: "/api/studio/diagrams/$diagramId";
      fullPath: "/api/studio/diagrams/$diagramId";
      preLoaderRoute: typeof ApiStudioDiagramsDiagramIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/artifacts/$artifactId/patch": {
      id: "/api/v1/artifacts/$artifactId/patch";
      path: "/patch";
      fullPath: "/api/v1/artifacts/$artifactId/patch";
      preLoaderRoute: typeof ApiV1ArtifactsArtifactIdPatchRouteImport;
      parentRoute: typeof ApiV1ArtifactsArtifactIdRoute;
    };
  }
}

interface ApiStudioProjectsRouteChildren {
  ApiStudioProjectsFromArtifactRoute: typeof ApiStudioProjectsFromArtifactRoute;
}

const ApiStudioProjectsRouteChildren: ApiStudioProjectsRouteChildren = {
  ApiStudioProjectsFromArtifactRoute: ApiStudioProjectsFromArtifactRoute,
};

const ApiStudioProjectsRouteWithChildren =
  ApiStudioProjectsRoute._addFileChildren(ApiStudioProjectsRouteChildren);

interface ApiV1ArtifactsArtifactIdRouteChildren {
  ApiV1ArtifactsArtifactIdPatchRoute: typeof ApiV1ArtifactsArtifactIdPatchRoute;
}

const ApiV1ArtifactsArtifactIdRouteChildren: ApiV1ArtifactsArtifactIdRouteChildren =
  {
    ApiV1ArtifactsArtifactIdPatchRoute: ApiV1ArtifactsArtifactIdPatchRoute,
  };

const ApiV1ArtifactsArtifactIdRouteWithChildren =
  ApiV1ArtifactsArtifactIdRoute._addFileChildren(
    ApiV1ArtifactsArtifactIdRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodemodeExportHarnessRoute: CodemodeExportHarnessRoute,
  McpRoute: McpRoute,
  ProjectsRoute: ProjectsRoute,
  ApiChatRoute: ApiChatRoute,
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRoute,
  DiagramsDiagramIdRoute: DiagramsDiagramIdRoute,
  ExamplesExampleIdRoute: ExamplesExampleIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ApiStudioProjectsRoute: ApiStudioProjectsRouteWithChildren,
  ApiV1GenerateRoute: ApiV1GenerateRoute,
  ArtifactsArtifactIdEditRoute: ArtifactsArtifactIdEditRoute,
  DiagramsDiagramIdEditRoute: DiagramsDiagramIdEditRoute,
  ApiStudioDiagramsDiagramIdRoute: ApiStudioDiagramsDiagramIdRoute,
  ApiStudioProjectsProjectIdRoute: ApiStudioProjectsProjectIdRoute,
  ApiV1ArtifactsArtifactIdRoute: ApiV1ArtifactsArtifactIdRouteWithChildren,
  ApiV1FlowchartsBuildRoute: ApiV1FlowchartsBuildRoute,
  ApiV1MindmapsBuildRoute: ApiV1MindmapsBuildRoute,
  ApiV1SequencesBuildRoute: ApiV1SequencesBuildRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
